// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  type Config,
  type ClientOptions as DefaultClientOptions,
} from "@hey-api/client-axios";
import Cookies from "js-cookie";
import type { ClientOptions } from "./types.gen";

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends DefaultClientOptions = ClientOptions> =
  (
    override?: Config<DefaultClientOptions & T>
  ) => Config<Required<DefaultClientOptions> & T>;

const AUTH_TOKEN_KEY = "access_token";
const REFRESH_TOKEN_KEY = "refresh_token";

export const client = createClient();

client.setConfig({
  baseURL: "http://localhost:8000",
});

// Request Interceptor
client.instance.interceptors.request.use(config => {
  // Use Cookies instead of localStorage
  const token = Cookies.get(AUTH_TOKEN_KEY);
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Response Interceptor
client.instance.interceptors.response.use(
  response => response,
  async error => {
    const originalRequest = error.config;
    if (error.response?.status === 401 && !originalRequest._retry) {
      originalRequest._retry = true;
      try {
        const refreshToken = Cookies.get(REFRESH_TOKEN_KEY);
        if (!refreshToken) {
          throw new Error("No refresh token");
        }

        // Use fetch to avoid interceptor loop
        const baseURL = client.getConfig().baseURL || "http://localhost:8000";
        const response = await fetch(`${baseURL}/api/auth/refresh`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ refresh_token: refreshToken }),
        });

        const data = await response.json();

        if (response.ok && data.success) {
          const { access_token, refresh_token: newRefreshToken } = data.data;

          // Update cookies
          Cookies.set(AUTH_TOKEN_KEY, access_token, {
            secure: true,
            sameSite: "Strict",
          });
          if (newRefreshToken) {
            Cookies.set(REFRESH_TOKEN_KEY, newRefreshToken, {
              secure: true,
              sameSite: "Strict",
            });
          }

          client.instance.defaults.headers.common["Authorization"] =
            `Bearer ${access_token}`;
          originalRequest.headers["Authorization"] = `Bearer ${access_token}`;

          return client.instance(originalRequest);
        } else {
          throw new Error("Refresh failed");
        }
      } catch (err) {
        Cookies.remove(AUTH_TOKEN_KEY);
        Cookies.remove(REFRESH_TOKEN_KEY);
        // Optional: Redirect to login
        if (typeof window !== "undefined") {
          window.location.href = "/login";
        }
        return Promise.reject(err);
      }
    }
    return Promise.reject(error);
  }
);
