// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponse = {
  success: boolean;
  data?: unknown | null;
  message?: string | null;
};

export type ApiResponseClinicDto = {
  success: boolean;
  data?: ClinicDto | null;
  message?: string | null;
};

export type ApiResponseInvoiceDto = {
  success: boolean;
  data?: InvoiceDto | null;
  message?: string | null;
};

export type ApiResponseLabOrderDto = {
  success: boolean;
  data?: LabOrderDto | null;
  message?: string | null;
};

export type ApiResponseLabTestDto = {
  success: boolean;
  data?: LabTestDto | null;
  message?: string | null;
};

export type ApiResponseMedicalRecordDto = {
  success: boolean;
  data?: MedicalRecordDto | null;
  message?: string | null;
};

export type ApiResponseMedicineDto = {
  success: boolean;
  data?: MedicineDto | null;
  message?: string | null;
};

export type ApiResponseNoneType = {
  success: boolean;
  data?: null;
  message?: string | null;
};

export type ApiResponsePrescriptionDto = {
  success: boolean;
  data?: PrescriptionDto | null;
  message?: string | null;
};

export type ApiResponseReferralDto = {
  success: boolean;
  data?: ReferralDto | null;
  message?: string | null;
};

export type ApiResponseTokenDao = {
  success: boolean;
  data?: TokenDao | null;
  message?: string | null;
};

export type ApiResponseUserDao = {
  success: boolean;
  data?: UserDao | null;
  message?: string | null;
};

export type ApiResponseUserProfileDao = {
  success: boolean;
  data?: UserProfileDao | null;
  message?: string | null;
};

export type ApiResponseVisitDto = {
  success: boolean;
  data?: VisitDto | null;
  message?: string | null;
};

export type ApiResponseWearableMeasurementDto = {
  success: boolean;
  data?: WearableMeasurementDto | null;
  message?: string | null;
};

export enum BloodTypeEnum {
  A = "A",
  B = "B",
  AB = "AB",
  O = "O",
  "A+" = "A+",
  "A-" = "A-",
  "B+" = "B+",
  "B-" = "B-",
  "AB+" = "AB+",
  "AB-" = "AB-",
  "O+" = "O+",
  "O-" = "O-",
}

export type BodyLogoutApiAuthLogoutPost = {
  refresh_token: string;
};

export type BodyRefreshTokenApiAuthRefreshPost = {
  refresh_token: string;
};

export type ClinicCreateDto = {
  name: string;
};

export type ClinicDto = {
  name: string;
  id: string;
  created_at: string;
  updated_at: string;
};

export type ClinicUpdateDto = {
  name?: string | null;
};

/**
 * DTO for creating a doctor user with doctor profile fields
 */
export type CreateDoctorDto = {
  username: string;
  password: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  /**
   * Medical specialty
   */
  specialty?: string | null;
  /**
   * Surat Izin Praktek number
   */
  sip_number?: string | null;
  /**
   * Surat Tanda Registrasi (16 digits)
   */
  str_number?: string | null;
};

/**
 * DTO for creating a patient user with patient profile fields
 */
export type CreatePatientDto = {
  username: string;
  password: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  /**
   * NIK Indonesia (16 digits)
   */
  nik: string;
  /**
   * Date of birth
   */
  date_of_birth: string;
  /**
   * Gender (L/P)
   */
  gender: GenderEnum;
  /**
   * BPJS number (optional)
   */
  bpjs_number?: string | null;
  /**
   * Blood type
   */
  blood_type?: BloodTypeEnum | null;
  /**
   * Full address
   */
  address?: string | null;
  /**
   * Emergency contact name
   */
  emergency_contact_name?: string | null;
  /**
   * Emergency contact phone
   */
  emergency_contact_phone?: string | null;
};

/**
 * DTO for creating a staff user with staff profile fields
 */
export type CreateStaffDto = {
  username: string;
  password: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  /**
   * Staff department: Registration/Pharmacy/Laboratory/Cashier
   */
  department: StaffDepartmentEnum;
};

export type CreateUserDto = {
  username: string;
  password: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  /**
   * Role: admin, doctor, staff, or patient
   */
  role: string;
};

export type DoctorProfileDao = {
  id: string;
  specialty?: string | null;
  sip_number?: string | null;
  str_number?: string | null;
};

export type ErrorResponse = {
  success: boolean;
  data?: null;
  message?: string | null;
  errors?: Array<FieldError> | null;
};

/**
 * field validation error
 */
export type FieldError = {
  field: string;
  message: string;
  tag: string;
  details?: {
    [key: string]: unknown;
  };
};

export enum GenderEnum {
  L = "L",
  P = "P",
}

export type InvoiceCreateDto = {
  visit_id: string;
  items?: Array<InvoiceItemCreateDto> | null;
  notes?: string | null;
};

export type InvoiceDto = {
  notes?: string | null;
  payment_method?: string;
  id: string;
  visit_id: string;
  cashier_id: string;
  total_amount: number;
  amount_paid: number;
  payment_status: string;
  created_at: string;
  updated_at: string;
  items?: Array<InvoiceItemDto>;
  visit?: VisitDto | null;
};

export type InvoiceItemCreateDto = {
  item_type: string;
  description: string;
  quantity: number;
  unit_price: number;
};

export type InvoiceItemDto = {
  item_type: string;
  description: string;
  quantity: number;
  unit_price: number;
  id: string;
  invoice_id: string;
  subtotal: number;
};

export type InvoiceUpdateDto = {
  total_amount?: number | null;
  amount_paid?: number | null;
  payment_status?: string | null;
  payment_method?: string | null;
  notes?: string | null;
  items?: Array<InvoiceItemCreateDto> | null;
};

export type LabOrderCreateDto = {
  lab_test_id: string;
  notes?: string | null;
  visit_id: string;
};

export type LabOrderDto = {
  lab_test_id: string;
  notes?: string | null;
  id: string;
  visit_id: string;
  doctor_id: string;
  lab_staff_id?: string | null;
  order_status: string;
  created_at: string;
  updated_at: string;
  lab_test?: LabTestDto | null;
  visit?: VisitDto | null;
  result?: LabResultDto | null;
};

export type LabOrderUpdateStatusDto = {
  order_status: string;
  result?: LabResultBase | null;
};

export type LabResultBase = {
  result_value?: string | null;
  result_unit?: string | null;
  interpretation?: string | null;
};

export type LabResultDto = {
  result_value?: string | null;
  result_unit?: string | null;
  interpretation?: string | null;
  id: string;
  lab_order_id: string;
  attachment_url?: string | null;
  attachment_type?: string | null;
  created_at: string;
  updated_at: string;
};

export type LabTestCreateDto = {
  test_code: string;
  test_name: string;
  category?: string | null;
  unit?: string | null;
  reference_range?: string | null;
  price?: number;
  is_active?: boolean;
};

export type LabTestDto = {
  test_code: string;
  test_name: string;
  category?: string | null;
  unit?: string | null;
  reference_range?: string | null;
  price?: number;
  is_active?: boolean;
  id: string;
  created_at: string;
  updated_at: string;
};

export type LabTestUpdateDto = {
  test_code?: string | null;
  test_name?: string | null;
  category?: string | null;
  unit?: string | null;
  reference_range?: string | null;
  price?: number | null;
  is_active?: boolean | null;
};

export type LoginDto = {
  username: string;
  password: string;
};

export type MedicalRecordCreateDto = {
  anamnesis?: string | null;
  physical_exam?: string | null;
  diagnosis?: string | null;
  treatment_plan?: string | null;
  doctor_notes?: string | null;
  outcome?: OutcomeEnum | null;
  visit_id: string;
};

export type MedicalRecordDto = {
  anamnesis?: string | null;
  physical_exam?: string | null;
  diagnosis?: string | null;
  treatment_plan?: string | null;
  doctor_notes?: string | null;
  outcome?: OutcomeEnum | null;
  id: string;
  visit_id: string;
  created_at: string;
  updated_at: string;
};

export type MedicalRecordUpdateDto = {
  anamnesis?: string | null;
  physical_exam?: string | null;
  diagnosis?: string | null;
  treatment_plan?: string | null;
  doctor_notes?: string | null;
  outcome?: OutcomeEnum | null;
};

export type MedicineCreateDto = {
  medicine_code: string;
  medicine_name: string;
  unit?: string | null;
  unit_price?: number;
  is_active?: boolean;
};

export type MedicineDto = {
  medicine_code: string;
  medicine_name: string;
  unit?: string | null;
  unit_price?: number;
  is_active?: boolean;
  id: string;
  created_at: string;
  updated_at: string;
};

export type MedicineUpdateDto = {
  medicine_code?: string | null;
  medicine_name?: string | null;
  unit?: string | null;
  unit_price?: number | null;
  is_active?: boolean | null;
};

export enum OutcomeEnum {
  RECOVERED = "recovered",
  FOLLOW_UP = "follow_up",
  REFERRED = "referred",
  INPATIENT = "inpatient",
}

export type PaginatedApiResponseListClinicDto = {
  success: boolean;
  data?: Array<ClinicDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListInvoiceDto = {
  success: boolean;
  data?: Array<InvoiceDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListLabOrderDto = {
  success: boolean;
  data?: Array<LabOrderDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListLabTestDto = {
  success: boolean;
  data?: Array<LabTestDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListMedicalRecordDto = {
  success: boolean;
  data?: Array<MedicalRecordDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListMedicineDto = {
  success: boolean;
  data?: Array<MedicineDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListPrescriptionDto = {
  success: boolean;
  data?: Array<PrescriptionDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListReferralDto = {
  success: boolean;
  data?: Array<ReferralDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListUserDao = {
  success: boolean;
  data?: Array<UserDao> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListVisitDto = {
  success: boolean;
  data?: Array<VisitDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginatedApiResponseListWearableMeasurementDto = {
  success: boolean;
  data?: Array<WearableMeasurementDto> | null;
  message?: string | null;
  meta:
    | PaginationMetaModel
    | {
        [key: string]: unknown;
      };
};

export type PaginationMetaModel = {
  limit: number;
  total: number;
  total_page: number;
  current_page: number;
};

export type PatientProfileDao = {
  nik: string;
  bpjs_number?: string | null;
  date_of_birth: string;
  gender: GenderEnum;
  blood_type?: BloodTypeEnum | null;
  address?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
};

export type PrescriptionCreateDto = {
  notes?: string | null;
  visit_id: string;
  items: Array<PrescriptionItemCreateDto>;
};

export type PrescriptionDto = {
  notes?: string | null;
  id: string;
  visit_id: string;
  doctor_id: string;
  pharmacy_staff_id?: string | null;
  prescription_status: string;
  created_at: string;
  updated_at: string;
  items?: Array<PrescriptionItemDto>;
  visit?: VisitDto | null;
};

export type PrescriptionItemCreateDto = {
  medicine_id: string;
  quantity: number;
  dosage?: string | null;
  frequency?: string | null;
  duration?: string | null;
  instructions?: string | null;
};

export type PrescriptionItemDto = {
  medicine_id: string;
  quantity: number;
  dosage?: string | null;
  frequency?: string | null;
  duration?: string | null;
  instructions?: string | null;
  id: string;
  prescription_id: string;
  medicine?: MedicineDto | null;
};

export enum PrescriptionStatusEnum {
  PENDING = "pending",
  PROCESSING = "processing",
  COMPLETED = "completed",
  CANCELED = "canceled",
}

export type PrescriptionUpdateDto = {
  notes?: string | null;
  items?: Array<PrescriptionItemCreateDto> | null;
};

export type PrescriptionUpdateStatusDto = {
  prescription_status: PrescriptionStatusEnum;
  pharmacy_staff_id?: string | null;
};

export type ReferralCreateDto = {
  referred_to_facility: string;
  specialty?: string | null;
  reason: string;
  diagnosis?: string | null;
  notes?: string | null;
  visit_id: string;
};

export type ReferralDto = {
  referred_to_facility: string;
  specialty?: string | null;
  reason: string;
  diagnosis?: string | null;
  notes?: string | null;
  id: string;
  visit_id: string;
  patient_id: string;
  referring_doctor_id: string;
  referral_status: string;
  attachment_url?: string | null;
  created_at: string;
  updated_at: string;
  visit?: VisitDto | null;
};

export type ReferralUpdateDto = {
  referred_to_facility?: string | null;
  specialty?: string | null;
  reason?: string | null;
  diagnosis?: string | null;
  notes?: string | null;
  referral_status?: string | null;
};

/**
 * Patient self-registration DTO with patient profile fields
 */
export type RegisterDto = {
  username: string;
  password: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  /**
   * NIK Indonesia (16 digits)
   */
  nik: string;
  /**
   * Date of birth
   */
  date_of_birth: string;
  /**
   * Gender (L/P)
   */
  gender: GenderEnum;
  /**
   * BPJS number (optional)
   */
  bpjs_number?: string | null;
  /**
   * Blood type
   */
  blood_type?: BloodTypeEnum | null;
  /**
   * Full address
   */
  address?: string | null;
  /**
   * Emergency contact name
   */
  emergency_contact_name?: string | null;
  /**
   * Emergency contact phone
   */
  emergency_contact_phone?: string | null;
};

export enum StaffDepartmentEnum {
  REGISTRATION = "Registration",
  PHARMACY = "Pharmacy",
  LABORATORY = "Laboratory",
  CASHIER = "Cashier",
}

export type StaffProfileDao = {
  department: StaffDepartmentEnum;
};

export type TokenDao = {
  access_token: string;
  refresh_token: string;
  token_type?: string;
};

export type UpdateAdminProfileDto = {
  full_name?: string | null;
  email?: string | null;
  phone_number?: string | null;
};

export type UpdateDoctorProfileDto = {
  full_name?: string | null;
  email?: string | null;
  phone_number?: string | null;
  specialty?: string | null;
  sip_number?: string | null;
  str_number?: string | null;
};

export type UpdatePatientProfileDto = {
  full_name?: string | null;
  email?: string | null;
  phone_number?: string | null;
  nik?: string | null;
  bpjs_number?: string | null;
  date_of_birth?: string | null;
  gender?: GenderEnum | null;
  blood_type?: BloodTypeEnum | null;
  address?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
};

export type UpdateStaffProfileDto = {
  full_name?: string | null;
  email?: string | null;
  phone_number?: string | null;
  department?: StaffDepartmentEnum | null;
};

export type UpdateUserAdminDto = {
  full_name?: string | null;
  email?: string | null;
  phone_number?: string | null;
  is_active?: boolean | null;
};

export type UserDao = {
  id: string;
  username: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  role: string;
  photo_url?: string | null;
  is_active: boolean;
};

export type UserProfileDao = {
  id: string;
  username: string;
  full_name: string;
  email?: string | null;
  phone_number?: string | null;
  role: string;
  photo_url?: string | null;
  is_active: boolean;
  details?: StaffProfileDao | DoctorProfileDao | PatientProfileDao | null;
};

export type VisitCreateDto = {
  visit_type?: VisitTypeEnum;
  chief_complaint?: string | null;
  visit_datetime?: string;
  patient_user_id: string;
  doctor_user_id: string;
  clinic_id: string;
};

export type VisitDto = {
  visit_type?: VisitTypeEnum;
  chief_complaint?: string | null;
  visit_datetime?: string;
  id: string;
  patient_id: string;
  doctor_id: string;
  registration_staff_id: string;
  clinic_id: string;
  queue_number: number | null;
  visit_status: VisitStatusEnum;
  created_at: string;
  updated_at: string;
};

export enum VisitStatusEnum {
  REGISTERED = "registered",
  EXAMINING = "examining",
  COMPLETED = "completed",
  CANCELED = "canceled",
}

export enum VisitTypeEnum {
  GENERAL = "general",
  FOLLOW_UP = "follow_up",
  REFERRAL = "referral",
  EMERGENCY = "emergency",
}

export type VisitUpdateDto = {
  visit_type?: VisitTypeEnum | null;
  chief_complaint?: string | null;
  visit_datetime?: string | null;
  visit_status?: VisitStatusEnum | null;
  doctor_id?: string | null;
  clinic_id?: string | null;
};

export type WearableMeasurementCreateDto = {
  recorded_at: string;
  heart_rate?: number | null;
  body_temperature?: number | null;
  spo2?: number | null;
};

export type WearableMeasurementDto = {
  recorded_at: string;
  heart_rate?: number | null;
  body_temperature?: number | null;
  spo2?: number | null;
  id: string;
  patient_id: string;
  created_at: string;
};

export type LoginApiAuthLoginPostData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type LoginApiAuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type LoginApiAuthLoginPostError =
  LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseTokenDao;
};

export type LoginApiAuthLoginPostResponse =
  LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type LogoutApiAuthLogoutPostData = {
  body: BodyLogoutApiAuthLogoutPost;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type LogoutApiAuthLogoutPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type LogoutApiAuthLogoutPostError =
  LogoutApiAuthLogoutPostErrors[keyof LogoutApiAuthLogoutPostErrors];

export type LogoutApiAuthLogoutPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseNoneType;
};

export type LogoutApiAuthLogoutPostResponse =
  LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type RefreshTokenApiAuthRefreshPostData = {
  body: BodyRefreshTokenApiAuthRefreshPost;
  path?: never;
  query?: never;
  url: "/api/auth/refresh";
};

export type RefreshTokenApiAuthRefreshPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type RefreshTokenApiAuthRefreshPostError =
  RefreshTokenApiAuthRefreshPostErrors[keyof RefreshTokenApiAuthRefreshPostErrors];

export type RefreshTokenApiAuthRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseTokenDao;
};

export type RefreshTokenApiAuthRefreshPostResponse =
  RefreshTokenApiAuthRefreshPostResponses[keyof RefreshTokenApiAuthRefreshPostResponses];

export type RegisterApiAuthRegisterPostData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: "/api/auth/register";
};

export type RegisterApiAuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type RegisterApiAuthRegisterPostError =
  RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserDao;
};

export type RegisterApiAuthRegisterPostResponse =
  RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type ListUsersApiUsersGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string | null;
    roles?: string | null;
  };
  url: "/api/users";
};

export type ListUsersApiUsersGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListUsersApiUsersGetError =
  ListUsersApiUsersGetErrors[keyof ListUsersApiUsersGetErrors];

export type ListUsersApiUsersGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListUserDao;
};

export type ListUsersApiUsersGetResponse =
  ListUsersApiUsersGetResponses[keyof ListUsersApiUsersGetResponses];

export type CreateUserApiUsersPostData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type CreateUserApiUsersPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateUserApiUsersPostError =
  CreateUserApiUsersPostErrors[keyof CreateUserApiUsersPostErrors];

export type CreateUserApiUsersPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserDao;
};

export type CreateUserApiUsersPostResponse =
  CreateUserApiUsersPostResponses[keyof CreateUserApiUsersPostResponses];

export type UpdateUserApiUsersUserIdPatchData = {
  body: UpdateUserAdminDto;
  path: {
    user_id: string;
  };
  query?: never;
  url: "/api/users/{user_id}";
};

export type UpdateUserApiUsersUserIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateUserApiUsersUserIdPatchError =
  UpdateUserApiUsersUserIdPatchErrors[keyof UpdateUserApiUsersUserIdPatchErrors];

export type UpdateUserApiUsersUserIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserDao;
};

export type UpdateUserApiUsersUserIdPatchResponse =
  UpdateUserApiUsersUserIdPatchResponses[keyof UpdateUserApiUsersUserIdPatchResponses];

export type CreatePatientUserApiUsersPatientsPostData = {
  body: CreatePatientDto;
  path?: never;
  query?: never;
  url: "/api/users/patients";
};

export type CreatePatientUserApiUsersPatientsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreatePatientUserApiUsersPatientsPostError =
  CreatePatientUserApiUsersPatientsPostErrors[keyof CreatePatientUserApiUsersPatientsPostErrors];

export type CreatePatientUserApiUsersPatientsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserDao;
};

export type CreatePatientUserApiUsersPatientsPostResponse =
  CreatePatientUserApiUsersPatientsPostResponses[keyof CreatePatientUserApiUsersPatientsPostResponses];

export type CreateDoctorUserApiUsersDoctorsPostData = {
  body: CreateDoctorDto;
  path?: never;
  query?: never;
  url: "/api/users/doctors";
};

export type CreateDoctorUserApiUsersDoctorsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateDoctorUserApiUsersDoctorsPostError =
  CreateDoctorUserApiUsersDoctorsPostErrors[keyof CreateDoctorUserApiUsersDoctorsPostErrors];

export type CreateDoctorUserApiUsersDoctorsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserDao;
};

export type CreateDoctorUserApiUsersDoctorsPostResponse =
  CreateDoctorUserApiUsersDoctorsPostResponses[keyof CreateDoctorUserApiUsersDoctorsPostResponses];

export type CreateStaffUserApiUsersStaffPostData = {
  body: CreateStaffDto;
  path?: never;
  query?: never;
  url: "/api/users/staff";
};

export type CreateStaffUserApiUsersStaffPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateStaffUserApiUsersStaffPostError =
  CreateStaffUserApiUsersStaffPostErrors[keyof CreateStaffUserApiUsersStaffPostErrors];

export type CreateStaffUserApiUsersStaffPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserDao;
};

export type CreateStaffUserApiUsersStaffPostResponse =
  CreateStaffUserApiUsersStaffPostResponses[keyof CreateStaffUserApiUsersStaffPostResponses];

export type ListClinicsApiClinicsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string | null;
  };
  url: "/api/clinics";
};

export type ListClinicsApiClinicsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListClinicsApiClinicsGetError =
  ListClinicsApiClinicsGetErrors[keyof ListClinicsApiClinicsGetErrors];

export type ListClinicsApiClinicsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListClinicDto;
};

export type ListClinicsApiClinicsGetResponse =
  ListClinicsApiClinicsGetResponses[keyof ListClinicsApiClinicsGetResponses];

export type CreateClinicApiClinicsPostData = {
  body: ClinicCreateDto;
  path?: never;
  query?: never;
  url: "/api/clinics";
};

export type CreateClinicApiClinicsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateClinicApiClinicsPostError =
  CreateClinicApiClinicsPostErrors[keyof CreateClinicApiClinicsPostErrors];

export type CreateClinicApiClinicsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseClinicDto;
};

export type CreateClinicApiClinicsPostResponse =
  CreateClinicApiClinicsPostResponses[keyof CreateClinicApiClinicsPostResponses];

export type DeleteClinicApiClinicsClinicIdDeleteData = {
  body?: never;
  path: {
    clinic_id: string;
  };
  query?: never;
  url: "/api/clinics/{clinic_id}";
};

export type DeleteClinicApiClinicsClinicIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteClinicApiClinicsClinicIdDeleteError =
  DeleteClinicApiClinicsClinicIdDeleteErrors[keyof DeleteClinicApiClinicsClinicIdDeleteErrors];

export type DeleteClinicApiClinicsClinicIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteClinicApiClinicsClinicIdDeleteResponse =
  DeleteClinicApiClinicsClinicIdDeleteResponses[keyof DeleteClinicApiClinicsClinicIdDeleteResponses];

export type GetClinicApiClinicsClinicIdGetData = {
  body?: never;
  path: {
    clinic_id: string;
  };
  query?: never;
  url: "/api/clinics/{clinic_id}";
};

export type GetClinicApiClinicsClinicIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetClinicApiClinicsClinicIdGetError =
  GetClinicApiClinicsClinicIdGetErrors[keyof GetClinicApiClinicsClinicIdGetErrors];

export type GetClinicApiClinicsClinicIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseClinicDto;
};

export type GetClinicApiClinicsClinicIdGetResponse =
  GetClinicApiClinicsClinicIdGetResponses[keyof GetClinicApiClinicsClinicIdGetResponses];

export type UpdateClinicApiClinicsClinicIdPatchData = {
  body: ClinicUpdateDto;
  path: {
    clinic_id: string;
  };
  query?: never;
  url: "/api/clinics/{clinic_id}";
};

export type UpdateClinicApiClinicsClinicIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateClinicApiClinicsClinicIdPatchError =
  UpdateClinicApiClinicsClinicIdPatchErrors[keyof UpdateClinicApiClinicsClinicIdPatchErrors];

export type UpdateClinicApiClinicsClinicIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseClinicDto;
};

export type UpdateClinicApiClinicsClinicIdPatchResponse =
  UpdateClinicApiClinicsClinicIdPatchResponses[keyof UpdateClinicApiClinicsClinicIdPatchResponses];

export type GetMyProfileApiProfileMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/profile/me";
};

export type GetMyProfileApiProfileMeGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetMyProfileApiProfileMeGetError =
  GetMyProfileApiProfileMeGetErrors[keyof GetMyProfileApiProfileMeGetErrors];

export type GetMyProfileApiProfileMeGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserProfileDao;
};

export type GetMyProfileApiProfileMeGetResponse =
  GetMyProfileApiProfileMeGetResponses[keyof GetMyProfileApiProfileMeGetResponses];

export type UpdateAdminProfileApiProfileAdminPatchData = {
  body: UpdateAdminProfileDto;
  path?: never;
  query?: never;
  url: "/api/profile/admin";
};

export type UpdateAdminProfileApiProfileAdminPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateAdminProfileApiProfileAdminPatchError =
  UpdateAdminProfileApiProfileAdminPatchErrors[keyof UpdateAdminProfileApiProfileAdminPatchErrors];

export type UpdateAdminProfileApiProfileAdminPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type UpdateAdminProfileApiProfileAdminPatchResponse =
  UpdateAdminProfileApiProfileAdminPatchResponses[keyof UpdateAdminProfileApiProfileAdminPatchResponses];

export type UpdateStaffProfileApiProfileStaffPatchData = {
  body: UpdateStaffProfileDto;
  path?: never;
  query?: never;
  url: "/api/profile/staff";
};

export type UpdateStaffProfileApiProfileStaffPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateStaffProfileApiProfileStaffPatchError =
  UpdateStaffProfileApiProfileStaffPatchErrors[keyof UpdateStaffProfileApiProfileStaffPatchErrors];

export type UpdateStaffProfileApiProfileStaffPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserProfileDao;
};

export type UpdateStaffProfileApiProfileStaffPatchResponse =
  UpdateStaffProfileApiProfileStaffPatchResponses[keyof UpdateStaffProfileApiProfileStaffPatchResponses];

export type UpdateDoctorProfileApiProfileDoctorPatchData = {
  body: UpdateDoctorProfileDto;
  path?: never;
  query?: never;
  url: "/api/profile/doctor";
};

export type UpdateDoctorProfileApiProfileDoctorPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateDoctorProfileApiProfileDoctorPatchError =
  UpdateDoctorProfileApiProfileDoctorPatchErrors[keyof UpdateDoctorProfileApiProfileDoctorPatchErrors];

export type UpdateDoctorProfileApiProfileDoctorPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserProfileDao;
};

export type UpdateDoctorProfileApiProfileDoctorPatchResponse =
  UpdateDoctorProfileApiProfileDoctorPatchResponses[keyof UpdateDoctorProfileApiProfileDoctorPatchResponses];

export type UpdatePatientProfileApiProfilePatientPatchData = {
  body: UpdatePatientProfileDto;
  path?: never;
  query?: never;
  url: "/api/profile/patient";
};

export type UpdatePatientProfileApiProfilePatientPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdatePatientProfileApiProfilePatientPatchError =
  UpdatePatientProfileApiProfilePatientPatchErrors[keyof UpdatePatientProfileApiProfilePatientPatchErrors];

export type UpdatePatientProfileApiProfilePatientPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseUserProfileDao;
};

export type UpdatePatientProfileApiProfilePatientPatchResponse =
  UpdatePatientProfileApiProfilePatientPatchResponses[keyof UpdatePatientProfileApiProfilePatientPatchResponses];

export type ListVisitsApiVisitsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    visit_status?: string | null;
    date_from?: string | null;
    date_to?: string | null;
  };
  url: "/api/visits";
};

export type ListVisitsApiVisitsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListVisitsApiVisitsGetError =
  ListVisitsApiVisitsGetErrors[keyof ListVisitsApiVisitsGetErrors];

export type ListVisitsApiVisitsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListVisitDto;
};

export type ListVisitsApiVisitsGetResponse =
  ListVisitsApiVisitsGetResponses[keyof ListVisitsApiVisitsGetResponses];

export type CreateVisitApiVisitsPostData = {
  body: VisitCreateDto;
  path?: never;
  query?: never;
  url: "/api/visits";
};

export type CreateVisitApiVisitsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateVisitApiVisitsPostError =
  CreateVisitApiVisitsPostErrors[keyof CreateVisitApiVisitsPostErrors];

export type CreateVisitApiVisitsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseVisitDto;
};

export type CreateVisitApiVisitsPostResponse =
  CreateVisitApiVisitsPostResponses[keyof CreateVisitApiVisitsPostResponses];

export type DeleteVisitApiVisitsVisitIdDeleteData = {
  body?: never;
  path: {
    visit_id: string;
  };
  query?: never;
  url: "/api/visits/{visit_id}";
};

export type DeleteVisitApiVisitsVisitIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteVisitApiVisitsVisitIdDeleteError =
  DeleteVisitApiVisitsVisitIdDeleteErrors[keyof DeleteVisitApiVisitsVisitIdDeleteErrors];

export type DeleteVisitApiVisitsVisitIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteVisitApiVisitsVisitIdDeleteResponse =
  DeleteVisitApiVisitsVisitIdDeleteResponses[keyof DeleteVisitApiVisitsVisitIdDeleteResponses];

export type GetVisitApiVisitsVisitIdGetData = {
  body?: never;
  path: {
    visit_id: string;
  };
  query?: never;
  url: "/api/visits/{visit_id}";
};

export type GetVisitApiVisitsVisitIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetVisitApiVisitsVisitIdGetError =
  GetVisitApiVisitsVisitIdGetErrors[keyof GetVisitApiVisitsVisitIdGetErrors];

export type GetVisitApiVisitsVisitIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseVisitDto;
};

export type GetVisitApiVisitsVisitIdGetResponse =
  GetVisitApiVisitsVisitIdGetResponses[keyof GetVisitApiVisitsVisitIdGetResponses];

export type UpdateVisitApiVisitsVisitIdPatchData = {
  body: VisitUpdateDto;
  path: {
    visit_id: string;
  };
  query?: never;
  url: "/api/visits/{visit_id}";
};

export type UpdateVisitApiVisitsVisitIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateVisitApiVisitsVisitIdPatchError =
  UpdateVisitApiVisitsVisitIdPatchErrors[keyof UpdateVisitApiVisitsVisitIdPatchErrors];

export type UpdateVisitApiVisitsVisitIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseVisitDto;
};

export type UpdateVisitApiVisitsVisitIdPatchResponse =
  UpdateVisitApiVisitsVisitIdPatchResponses[keyof UpdateVisitApiVisitsVisitIdPatchResponses];

export type ListMedicalRecordsApiMedicalRecordsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    patient_id?: string | null;
    doctor_id?: string | null;
    visit_id?: string | null;
  };
  url: "/api/medical-records";
};

export type ListMedicalRecordsApiMedicalRecordsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListMedicalRecordsApiMedicalRecordsGetError =
  ListMedicalRecordsApiMedicalRecordsGetErrors[keyof ListMedicalRecordsApiMedicalRecordsGetErrors];

export type ListMedicalRecordsApiMedicalRecordsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListMedicalRecordDto;
};

export type ListMedicalRecordsApiMedicalRecordsGetResponse =
  ListMedicalRecordsApiMedicalRecordsGetResponses[keyof ListMedicalRecordsApiMedicalRecordsGetResponses];

export type CreateMedicalRecordApiMedicalRecordsPostData = {
  body: MedicalRecordCreateDto;
  path?: never;
  query?: never;
  url: "/api/medical-records";
};

export type CreateMedicalRecordApiMedicalRecordsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateMedicalRecordApiMedicalRecordsPostError =
  CreateMedicalRecordApiMedicalRecordsPostErrors[keyof CreateMedicalRecordApiMedicalRecordsPostErrors];

export type CreateMedicalRecordApiMedicalRecordsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseMedicalRecordDto;
};

export type CreateMedicalRecordApiMedicalRecordsPostResponse =
  CreateMedicalRecordApiMedicalRecordsPostResponses[keyof CreateMedicalRecordApiMedicalRecordsPostResponses];

export type DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteData = {
  body?: never;
  path: {
    record_id: string;
  };
  query?: never;
  url: "/api/medical-records/{record_id}";
};

export type DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteError =
  DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteErrors[keyof DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteErrors];

export type DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteResponse =
  DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteResponses[keyof DeleteMedicalRecordApiMedicalRecordsRecordIdDeleteResponses];

export type GetMedicalRecordApiMedicalRecordsRecordIdGetData = {
  body?: never;
  path: {
    record_id: string;
  };
  query?: never;
  url: "/api/medical-records/{record_id}";
};

export type GetMedicalRecordApiMedicalRecordsRecordIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetMedicalRecordApiMedicalRecordsRecordIdGetError =
  GetMedicalRecordApiMedicalRecordsRecordIdGetErrors[keyof GetMedicalRecordApiMedicalRecordsRecordIdGetErrors];

export type GetMedicalRecordApiMedicalRecordsRecordIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseMedicalRecordDto;
};

export type GetMedicalRecordApiMedicalRecordsRecordIdGetResponse =
  GetMedicalRecordApiMedicalRecordsRecordIdGetResponses[keyof GetMedicalRecordApiMedicalRecordsRecordIdGetResponses];

export type UpdateMedicalRecordApiMedicalRecordsRecordIdPatchData = {
  body: MedicalRecordUpdateDto;
  path: {
    record_id: string;
  };
  query?: never;
  url: "/api/medical-records/{record_id}";
};

export type UpdateMedicalRecordApiMedicalRecordsRecordIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateMedicalRecordApiMedicalRecordsRecordIdPatchError =
  UpdateMedicalRecordApiMedicalRecordsRecordIdPatchErrors[keyof UpdateMedicalRecordApiMedicalRecordsRecordIdPatchErrors];

export type UpdateMedicalRecordApiMedicalRecordsRecordIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseMedicalRecordDto;
};

export type UpdateMedicalRecordApiMedicalRecordsRecordIdPatchResponse =
  UpdateMedicalRecordApiMedicalRecordsRecordIdPatchResponses[keyof UpdateMedicalRecordApiMedicalRecordsRecordIdPatchResponses];

export type ListMedicinesApiMedicinesGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
  };
  url: "/api/medicines";
};

export type ListMedicinesApiMedicinesGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListMedicinesApiMedicinesGetError =
  ListMedicinesApiMedicinesGetErrors[keyof ListMedicinesApiMedicinesGetErrors];

export type ListMedicinesApiMedicinesGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListMedicineDto;
};

export type ListMedicinesApiMedicinesGetResponse =
  ListMedicinesApiMedicinesGetResponses[keyof ListMedicinesApiMedicinesGetResponses];

export type CreateMedicineApiMedicinesPostData = {
  body: MedicineCreateDto;
  path?: never;
  query?: never;
  url: "/api/medicines";
};

export type CreateMedicineApiMedicinesPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateMedicineApiMedicinesPostError =
  CreateMedicineApiMedicinesPostErrors[keyof CreateMedicineApiMedicinesPostErrors];

export type CreateMedicineApiMedicinesPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseMedicineDto;
};

export type CreateMedicineApiMedicinesPostResponse =
  CreateMedicineApiMedicinesPostResponses[keyof CreateMedicineApiMedicinesPostResponses];

export type DeleteMedicineApiMedicinesMedicineIdDeleteData = {
  body?: never;
  path: {
    medicine_id: string;
  };
  query?: never;
  url: "/api/medicines/{medicine_id}";
};

export type DeleteMedicineApiMedicinesMedicineIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteMedicineApiMedicinesMedicineIdDeleteError =
  DeleteMedicineApiMedicinesMedicineIdDeleteErrors[keyof DeleteMedicineApiMedicinesMedicineIdDeleteErrors];

export type DeleteMedicineApiMedicinesMedicineIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteMedicineApiMedicinesMedicineIdDeleteResponse =
  DeleteMedicineApiMedicinesMedicineIdDeleteResponses[keyof DeleteMedicineApiMedicinesMedicineIdDeleteResponses];

export type GetMedicineApiMedicinesMedicineIdGetData = {
  body?: never;
  path: {
    medicine_id: string;
  };
  query?: never;
  url: "/api/medicines/{medicine_id}";
};

export type GetMedicineApiMedicinesMedicineIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetMedicineApiMedicinesMedicineIdGetError =
  GetMedicineApiMedicinesMedicineIdGetErrors[keyof GetMedicineApiMedicinesMedicineIdGetErrors];

export type GetMedicineApiMedicinesMedicineIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseMedicineDto;
};

export type GetMedicineApiMedicinesMedicineIdGetResponse =
  GetMedicineApiMedicinesMedicineIdGetResponses[keyof GetMedicineApiMedicinesMedicineIdGetResponses];

export type UpdateMedicineApiMedicinesMedicineIdPatchData = {
  body: MedicineUpdateDto;
  path: {
    medicine_id: string;
  };
  query?: never;
  url: "/api/medicines/{medicine_id}";
};

export type UpdateMedicineApiMedicinesMedicineIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateMedicineApiMedicinesMedicineIdPatchError =
  UpdateMedicineApiMedicinesMedicineIdPatchErrors[keyof UpdateMedicineApiMedicinesMedicineIdPatchErrors];

export type UpdateMedicineApiMedicinesMedicineIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseMedicineDto;
};

export type UpdateMedicineApiMedicinesMedicineIdPatchResponse =
  UpdateMedicineApiMedicinesMedicineIdPatchResponses[keyof UpdateMedicineApiMedicinesMedicineIdPatchResponses];

export type ListPrescriptionsApiPrescriptionsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string | null;
    status?: string | null;
    visit_id?: string | null;
  };
  url: "/api/prescriptions";
};

export type ListPrescriptionsApiPrescriptionsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListPrescriptionsApiPrescriptionsGetError =
  ListPrescriptionsApiPrescriptionsGetErrors[keyof ListPrescriptionsApiPrescriptionsGetErrors];

export type ListPrescriptionsApiPrescriptionsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListPrescriptionDto;
};

export type ListPrescriptionsApiPrescriptionsGetResponse =
  ListPrescriptionsApiPrescriptionsGetResponses[keyof ListPrescriptionsApiPrescriptionsGetResponses];

export type CreatePrescriptionApiPrescriptionsPostData = {
  body: PrescriptionCreateDto;
  path?: never;
  query?: never;
  url: "/api/prescriptions";
};

export type CreatePrescriptionApiPrescriptionsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreatePrescriptionApiPrescriptionsPostError =
  CreatePrescriptionApiPrescriptionsPostErrors[keyof CreatePrescriptionApiPrescriptionsPostErrors];

export type CreatePrescriptionApiPrescriptionsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponsePrescriptionDto;
};

export type CreatePrescriptionApiPrescriptionsPostResponse =
  CreatePrescriptionApiPrescriptionsPostResponses[keyof CreatePrescriptionApiPrescriptionsPostResponses];

export type GetPrescriptionApiPrescriptionsPrescriptionIdGetData = {
  body?: never;
  path: {
    prescription_id: string;
  };
  query?: never;
  url: "/api/prescriptions/{prescription_id}";
};

export type GetPrescriptionApiPrescriptionsPrescriptionIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetPrescriptionApiPrescriptionsPrescriptionIdGetError =
  GetPrescriptionApiPrescriptionsPrescriptionIdGetErrors[keyof GetPrescriptionApiPrescriptionsPrescriptionIdGetErrors];

export type GetPrescriptionApiPrescriptionsPrescriptionIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponsePrescriptionDto;
};

export type GetPrescriptionApiPrescriptionsPrescriptionIdGetResponse =
  GetPrescriptionApiPrescriptionsPrescriptionIdGetResponses[keyof GetPrescriptionApiPrescriptionsPrescriptionIdGetResponses];

export type UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchData = {
  body: PrescriptionUpdateDto;
  path: {
    prescription_id: string;
  };
  query?: never;
  url: "/api/prescriptions/{prescription_id}";
};

export type UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchError =
  UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchErrors[keyof UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchErrors];

export type UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponsePrescriptionDto;
};

export type UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchResponse =
  UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchResponses[keyof UpdatePrescriptionApiPrescriptionsPrescriptionIdPatchResponses];

export type UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchData =
  {
    body: PrescriptionUpdateStatusDto;
    path: {
      prescription_id: string;
    };
    query?: never;
    url: "/api/prescriptions/{prescription_id}/status";
  };

export type UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchErrors =
  {
    /**
     * Validation Error
     */
    422: ErrorResponse;
  };

export type UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchError =
  UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchErrors[keyof UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchErrors];

export type UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchResponses =
  {
    /**
     * Successful Response
     */
    200: ApiResponsePrescriptionDto;
  };

export type UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchResponse =
  UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchResponses[keyof UpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchResponses];

export type ListLabTestsApiLabTestsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string | null;
    category?: string | null;
  };
  url: "/api/lab/tests";
};

export type ListLabTestsApiLabTestsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListLabTestsApiLabTestsGetError =
  ListLabTestsApiLabTestsGetErrors[keyof ListLabTestsApiLabTestsGetErrors];

export type ListLabTestsApiLabTestsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListLabTestDto;
};

export type ListLabTestsApiLabTestsGetResponse =
  ListLabTestsApiLabTestsGetResponses[keyof ListLabTestsApiLabTestsGetResponses];

export type CreateLabTestApiLabTestsPostData = {
  body: LabTestCreateDto;
  path?: never;
  query?: never;
  url: "/api/lab/tests";
};

export type CreateLabTestApiLabTestsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateLabTestApiLabTestsPostError =
  CreateLabTestApiLabTestsPostErrors[keyof CreateLabTestApiLabTestsPostErrors];

export type CreateLabTestApiLabTestsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLabTestDto;
};

export type CreateLabTestApiLabTestsPostResponse =
  CreateLabTestApiLabTestsPostResponses[keyof CreateLabTestApiLabTestsPostResponses];

export type DeleteLabTestApiLabTestsTestIdDeleteData = {
  body?: never;
  path: {
    test_id: string;
  };
  query?: never;
  url: "/api/lab/tests/{test_id}";
};

export type DeleteLabTestApiLabTestsTestIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteLabTestApiLabTestsTestIdDeleteError =
  DeleteLabTestApiLabTestsTestIdDeleteErrors[keyof DeleteLabTestApiLabTestsTestIdDeleteErrors];

export type DeleteLabTestApiLabTestsTestIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteLabTestApiLabTestsTestIdDeleteResponse =
  DeleteLabTestApiLabTestsTestIdDeleteResponses[keyof DeleteLabTestApiLabTestsTestIdDeleteResponses];

export type GetLabTestApiLabTestsTestIdGetData = {
  body?: never;
  path: {
    test_id: string;
  };
  query?: never;
  url: "/api/lab/tests/{test_id}";
};

export type GetLabTestApiLabTestsTestIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetLabTestApiLabTestsTestIdGetError =
  GetLabTestApiLabTestsTestIdGetErrors[keyof GetLabTestApiLabTestsTestIdGetErrors];

export type GetLabTestApiLabTestsTestIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLabTestDto;
};

export type GetLabTestApiLabTestsTestIdGetResponse =
  GetLabTestApiLabTestsTestIdGetResponses[keyof GetLabTestApiLabTestsTestIdGetResponses];

export type UpdateLabTestApiLabTestsTestIdPatchData = {
  body: LabTestUpdateDto;
  path: {
    test_id: string;
  };
  query?: never;
  url: "/api/lab/tests/{test_id}";
};

export type UpdateLabTestApiLabTestsTestIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateLabTestApiLabTestsTestIdPatchError =
  UpdateLabTestApiLabTestsTestIdPatchErrors[keyof UpdateLabTestApiLabTestsTestIdPatchErrors];

export type UpdateLabTestApiLabTestsTestIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLabTestDto;
};

export type UpdateLabTestApiLabTestsTestIdPatchResponse =
  UpdateLabTestApiLabTestsTestIdPatchResponses[keyof UpdateLabTestApiLabTestsTestIdPatchResponses];

export type ListLabOrdersApiLabOrdersGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    status?: string | null;
    visit_id?: string | null;
  };
  url: "/api/lab/orders";
};

export type ListLabOrdersApiLabOrdersGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListLabOrdersApiLabOrdersGetError =
  ListLabOrdersApiLabOrdersGetErrors[keyof ListLabOrdersApiLabOrdersGetErrors];

export type ListLabOrdersApiLabOrdersGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListLabOrderDto;
};

export type ListLabOrdersApiLabOrdersGetResponse =
  ListLabOrdersApiLabOrdersGetResponses[keyof ListLabOrdersApiLabOrdersGetResponses];

export type CreateLabOrderApiLabOrdersPostData = {
  body: LabOrderCreateDto;
  path?: never;
  query?: never;
  url: "/api/lab/orders";
};

export type CreateLabOrderApiLabOrdersPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateLabOrderApiLabOrdersPostError =
  CreateLabOrderApiLabOrdersPostErrors[keyof CreateLabOrderApiLabOrdersPostErrors];

export type CreateLabOrderApiLabOrdersPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLabOrderDto;
};

export type CreateLabOrderApiLabOrdersPostResponse =
  CreateLabOrderApiLabOrdersPostResponses[keyof CreateLabOrderApiLabOrdersPostResponses];

export type GetLabOrderApiLabOrdersOrderIdGetData = {
  body?: never;
  path: {
    order_id: string;
  };
  query?: never;
  url: "/api/lab/orders/{order_id}";
};

export type GetLabOrderApiLabOrdersOrderIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetLabOrderApiLabOrdersOrderIdGetError =
  GetLabOrderApiLabOrdersOrderIdGetErrors[keyof GetLabOrderApiLabOrdersOrderIdGetErrors];

export type GetLabOrderApiLabOrdersOrderIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLabOrderDto;
};

export type GetLabOrderApiLabOrdersOrderIdGetResponse =
  GetLabOrderApiLabOrdersOrderIdGetResponses[keyof GetLabOrderApiLabOrdersOrderIdGetResponses];

export type UpdateLabOrderApiLabOrdersOrderIdPatchData = {
  body: LabOrderUpdateStatusDto;
  path: {
    order_id: string;
  };
  query?: never;
  url: "/api/lab/orders/{order_id}";
};

export type UpdateLabOrderApiLabOrdersOrderIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateLabOrderApiLabOrdersOrderIdPatchError =
  UpdateLabOrderApiLabOrdersOrderIdPatchErrors[keyof UpdateLabOrderApiLabOrdersOrderIdPatchErrors];

export type UpdateLabOrderApiLabOrdersOrderIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLabOrderDto;
};

export type UpdateLabOrderApiLabOrdersOrderIdPatchResponse =
  UpdateLabOrderApiLabOrdersOrderIdPatchResponses[keyof UpdateLabOrderApiLabOrdersOrderIdPatchResponses];

export type ListReferralsApiReferralsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string | null;
  };
  url: "/api/referrals";
};

export type ListReferralsApiReferralsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListReferralsApiReferralsGetError =
  ListReferralsApiReferralsGetErrors[keyof ListReferralsApiReferralsGetErrors];

export type ListReferralsApiReferralsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListReferralDto;
};

export type ListReferralsApiReferralsGetResponse =
  ListReferralsApiReferralsGetResponses[keyof ListReferralsApiReferralsGetResponses];

export type CreateReferralApiReferralsPostData = {
  body: ReferralCreateDto;
  path?: never;
  query?: never;
  url: "/api/referrals";
};

export type CreateReferralApiReferralsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateReferralApiReferralsPostError =
  CreateReferralApiReferralsPostErrors[keyof CreateReferralApiReferralsPostErrors];

export type CreateReferralApiReferralsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseReferralDto;
};

export type CreateReferralApiReferralsPostResponse =
  CreateReferralApiReferralsPostResponses[keyof CreateReferralApiReferralsPostResponses];

export type DeleteReferralApiReferralsReferralIdDeleteData = {
  body?: never;
  path: {
    referral_id: string;
  };
  query?: never;
  url: "/api/referrals/{referral_id}";
};

export type DeleteReferralApiReferralsReferralIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteReferralApiReferralsReferralIdDeleteError =
  DeleteReferralApiReferralsReferralIdDeleteErrors[keyof DeleteReferralApiReferralsReferralIdDeleteErrors];

export type DeleteReferralApiReferralsReferralIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteReferralApiReferralsReferralIdDeleteResponse =
  DeleteReferralApiReferralsReferralIdDeleteResponses[keyof DeleteReferralApiReferralsReferralIdDeleteResponses];

export type GetReferralApiReferralsReferralIdGetData = {
  body?: never;
  path: {
    referral_id: string;
  };
  query?: never;
  url: "/api/referrals/{referral_id}";
};

export type GetReferralApiReferralsReferralIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetReferralApiReferralsReferralIdGetError =
  GetReferralApiReferralsReferralIdGetErrors[keyof GetReferralApiReferralsReferralIdGetErrors];

export type GetReferralApiReferralsReferralIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseReferralDto;
};

export type GetReferralApiReferralsReferralIdGetResponse =
  GetReferralApiReferralsReferralIdGetResponses[keyof GetReferralApiReferralsReferralIdGetResponses];

export type UpdateReferralApiReferralsReferralIdPatchData = {
  body: ReferralUpdateDto;
  path: {
    referral_id: string;
  };
  query?: never;
  url: "/api/referrals/{referral_id}";
};

export type UpdateReferralApiReferralsReferralIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateReferralApiReferralsReferralIdPatchError =
  UpdateReferralApiReferralsReferralIdPatchErrors[keyof UpdateReferralApiReferralsReferralIdPatchErrors];

export type UpdateReferralApiReferralsReferralIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseReferralDto;
};

export type UpdateReferralApiReferralsReferralIdPatchResponse =
  UpdateReferralApiReferralsReferralIdPatchResponses[keyof UpdateReferralApiReferralsReferralIdPatchResponses];

export type ListInvoicesApiInvoicesGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/api/invoices";
};

export type ListInvoicesApiInvoicesGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListInvoicesApiInvoicesGetError =
  ListInvoicesApiInvoicesGetErrors[keyof ListInvoicesApiInvoicesGetErrors];

export type ListInvoicesApiInvoicesGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListInvoiceDto;
};

export type ListInvoicesApiInvoicesGetResponse =
  ListInvoicesApiInvoicesGetResponses[keyof ListInvoicesApiInvoicesGetResponses];

export type CreateInvoiceApiInvoicesPostData = {
  body: InvoiceCreateDto;
  path?: never;
  query?: never;
  url: "/api/invoices";
};

export type CreateInvoiceApiInvoicesPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type CreateInvoiceApiInvoicesPostError =
  CreateInvoiceApiInvoicesPostErrors[keyof CreateInvoiceApiInvoicesPostErrors];

export type CreateInvoiceApiInvoicesPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseInvoiceDto;
};

export type CreateInvoiceApiInvoicesPostResponse =
  CreateInvoiceApiInvoicesPostResponses[keyof CreateInvoiceApiInvoicesPostResponses];

export type DeleteInvoiceApiInvoicesInvoiceIdDeleteData = {
  body?: never;
  path: {
    invoice_id: string;
  };
  query?: never;
  url: "/api/invoices/{invoice_id}";
};

export type DeleteInvoiceApiInvoicesInvoiceIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type DeleteInvoiceApiInvoicesInvoiceIdDeleteError =
  DeleteInvoiceApiInvoicesInvoiceIdDeleteErrors[keyof DeleteInvoiceApiInvoicesInvoiceIdDeleteErrors];

export type DeleteInvoiceApiInvoicesInvoiceIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse;
};

export type DeleteInvoiceApiInvoicesInvoiceIdDeleteResponse =
  DeleteInvoiceApiInvoicesInvoiceIdDeleteResponses[keyof DeleteInvoiceApiInvoicesInvoiceIdDeleteResponses];

export type GetInvoiceApiInvoicesInvoiceIdGetData = {
  body?: never;
  path: {
    invoice_id: string;
  };
  query?: never;
  url: "/api/invoices/{invoice_id}";
};

export type GetInvoiceApiInvoicesInvoiceIdGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type GetInvoiceApiInvoicesInvoiceIdGetError =
  GetInvoiceApiInvoicesInvoiceIdGetErrors[keyof GetInvoiceApiInvoicesInvoiceIdGetErrors];

export type GetInvoiceApiInvoicesInvoiceIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseInvoiceDto;
};

export type GetInvoiceApiInvoicesInvoiceIdGetResponse =
  GetInvoiceApiInvoicesInvoiceIdGetResponses[keyof GetInvoiceApiInvoicesInvoiceIdGetResponses];

export type UpdateInvoiceApiInvoicesInvoiceIdPatchData = {
  body: InvoiceUpdateDto;
  path: {
    invoice_id: string;
  };
  query?: never;
  url: "/api/invoices/{invoice_id}";
};

export type UpdateInvoiceApiInvoicesInvoiceIdPatchErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type UpdateInvoiceApiInvoicesInvoiceIdPatchError =
  UpdateInvoiceApiInvoicesInvoiceIdPatchErrors[keyof UpdateInvoiceApiInvoicesInvoiceIdPatchErrors];

export type UpdateInvoiceApiInvoicesInvoiceIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseInvoiceDto;
};

export type UpdateInvoiceApiInvoicesInvoiceIdPatchResponse =
  UpdateInvoiceApiInvoicesInvoiceIdPatchResponses[keyof UpdateInvoiceApiInvoicesInvoiceIdPatchResponses];

export type ListMeasurementsApiWearablesMeasurementsGetData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    date_from?: string | null;
    date_to?: string | null;
    patient_id?: string | null;
  };
  url: "/api/wearables/measurements";
};

export type ListMeasurementsApiWearablesMeasurementsGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type ListMeasurementsApiWearablesMeasurementsGetError =
  ListMeasurementsApiWearablesMeasurementsGetErrors[keyof ListMeasurementsApiWearablesMeasurementsGetErrors];

export type ListMeasurementsApiWearablesMeasurementsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedApiResponseListWearableMeasurementDto;
};

export type ListMeasurementsApiWearablesMeasurementsGetResponse =
  ListMeasurementsApiWearablesMeasurementsGetResponses[keyof ListMeasurementsApiWearablesMeasurementsGetResponses];

export type AddMeasurementApiWearablesMeasurementsPostData = {
  body: WearableMeasurementCreateDto;
  path?: never;
  query?: never;
  url: "/api/wearables/measurements";
};

export type AddMeasurementApiWearablesMeasurementsPostErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type AddMeasurementApiWearablesMeasurementsPostError =
  AddMeasurementApiWearablesMeasurementsPostErrors[keyof AddMeasurementApiWearablesMeasurementsPostErrors];

export type AddMeasurementApiWearablesMeasurementsPostResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseWearableMeasurementDto;
};

export type AddMeasurementApiWearablesMeasurementsPostResponse =
  AddMeasurementApiWearablesMeasurementsPostResponses[keyof AddMeasurementApiWearablesMeasurementsPostResponses];

export type HealthCheckApiHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type HealthCheckApiHealthGetErrors = {
  /**
   * Validation Error
   */
  422: ErrorResponse;
};

export type HealthCheckApiHealthGetError =
  HealthCheckApiHealthGetErrors[keyof HealthCheckApiHealthGetErrors];

export type HealthCheckApiHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};
