// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zApiResponse = z.object({
    success: z.boolean(),
    data: z.union([
        z.unknown(),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zClinicDto = z.object({
    name: z.string(),
    id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zApiResponseClinicDto = z.object({
    success: z.boolean(),
    data: z.union([
        zClinicDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zInvoiceItemDto = z.object({
    item_type: z.string(),
    description: z.string(),
    quantity: z.number().int(),
    unit_price: z.number().gte(0),
    id: z.string().uuid(),
    invoice_id: z.string().uuid(),
    subtotal: z.number()
});

export const zVisitTypeEnum = z.enum([
    'general',
    'follow_up',
    'referral',
    'emergency'
]);

export const zVisitStatusEnum = z.enum([
    'registered',
    'examining',
    'completed',
    'canceled'
]);

export const zVisitDto = z.object({
    visit_type: zVisitTypeEnum.optional(),
    chief_complaint: z.union([
        z.string(),
        z.null()
    ]).optional(),
    visit_datetime: z.string().datetime().optional(),
    id: z.string().uuid(),
    patient_id: z.string().uuid(),
    doctor_id: z.string().uuid(),
    registration_staff_id: z.string().uuid(),
    clinic_id: z.string().uuid(),
    queue_number: z.union([
        z.number().int(),
        z.null()
    ]),
    visit_status: zVisitStatusEnum,
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zInvoiceDto = z.object({
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    payment_method: z.string().optional().default('cash'),
    id: z.string().uuid(),
    visit_id: z.string().uuid(),
    cashier_id: z.string().uuid(),
    total_amount: z.number(),
    amount_paid: z.number(),
    payment_status: z.string(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    items: z.array(zInvoiceItemDto).optional().default([]),
    visit: z.union([
        zVisitDto,
        z.null()
    ]).optional()
});

export const zApiResponseInvoiceDto = z.object({
    success: z.boolean(),
    data: z.union([
        zInvoiceDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zLabTestDto = z.object({
    test_code: z.string(),
    test_name: z.string(),
    category: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reference_range: z.union([
        z.string(),
        z.null()
    ]).optional(),
    price: z.number().gte(0).optional().default(0),
    is_active: z.boolean().optional().default(true),
    id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zLabResultDto = z.object({
    result_value: z.union([
        z.string(),
        z.null()
    ]).optional(),
    result_unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    interpretation: z.union([
        z.string(),
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    lab_order_id: z.string().uuid(),
    attachment_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    attachment_type: z.union([
        z.string(),
        z.null()
    ]).optional(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zLabOrderDto = z.object({
    lab_test_id: z.string().uuid(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    visit_id: z.string().uuid(),
    doctor_id: z.string().uuid(),
    lab_staff_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    order_status: z.string(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    lab_test: z.union([
        zLabTestDto,
        z.null()
    ]).optional(),
    visit: z.union([
        zVisitDto,
        z.null()
    ]).optional(),
    result: z.union([
        zLabResultDto,
        z.null()
    ]).optional()
});

export const zApiResponseLabOrderDto = z.object({
    success: z.boolean(),
    data: z.union([
        zLabOrderDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zApiResponseLabTestDto = z.object({
    success: z.boolean(),
    data: z.union([
        zLabTestDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zOutcomeEnum = z.enum([
    'recovered',
    'follow_up',
    'referred',
    'inpatient'
]);

export const zMedicalRecordDto = z.object({
    anamnesis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    physical_exam: z.union([
        z.string(),
        z.null()
    ]).optional(),
    diagnosis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    treatment_plan: z.union([
        z.string(),
        z.null()
    ]).optional(),
    doctor_notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    outcome: z.union([
        zOutcomeEnum,
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    visit_id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zApiResponseMedicalRecordDto = z.object({
    success: z.boolean(),
    data: z.union([
        zMedicalRecordDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zMedicineDto = z.object({
    medicine_code: z.string(),
    medicine_name: z.string(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit_price: z.number().optional().default(0),
    is_active: z.boolean().optional().default(true),
    id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zApiResponseMedicineDto = z.object({
    success: z.boolean(),
    data: z.union([
        zMedicineDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zApiResponseNoneType = z.object({
    success: z.boolean(),
    data: z.null().optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zPrescriptionItemDto = z.object({
    medicine_id: z.string().uuid(),
    quantity: z.number().int(),
    dosage: z.union([
        z.string(),
        z.null()
    ]).optional(),
    frequency: z.union([
        z.string(),
        z.null()
    ]).optional(),
    duration: z.union([
        z.string(),
        z.null()
    ]).optional(),
    instructions: z.union([
        z.string(),
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    prescription_id: z.string().uuid(),
    medicine: z.union([
        zMedicineDto,
        z.null()
    ]).optional()
});

export const zPrescriptionDto = z.object({
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    visit_id: z.string().uuid(),
    doctor_id: z.string().uuid(),
    pharmacy_staff_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    prescription_status: z.string(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    items: z.array(zPrescriptionItemDto).optional().default([]),
    visit: z.union([
        zVisitDto,
        z.null()
    ]).optional()
});

export const zApiResponsePrescriptionDto = z.object({
    success: z.boolean(),
    data: z.union([
        zPrescriptionDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zReferralDto = z.object({
    referred_to_facility: z.string(),
    specialty: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reason: z.string(),
    diagnosis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    visit_id: z.string().uuid(),
    patient_id: z.string().uuid(),
    referring_doctor_id: z.string().uuid(),
    referral_status: z.string(),
    attachment_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    visit: z.union([
        zVisitDto,
        z.null()
    ]).optional()
});

export const zApiResponseReferralDto = z.object({
    success: z.boolean(),
    data: z.union([
        zReferralDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zTokenDao = z.object({
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

export const zApiResponseTokenDao = z.object({
    success: z.boolean(),
    data: z.union([
        zTokenDao,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUserDao = z.object({
    id: z.string().uuid(),
    username: z.string(),
    full_name: z.string(),
    email: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    role: z.string(),
    photo_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    is_active: z.boolean()
});

export const zApiResponseUserDao = z.object({
    success: z.boolean(),
    data: z.union([
        zUserDao,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zStaffDepartmentEnum = z.enum([
    'Registration',
    'Pharmacy',
    'Laboratory',
    'Cashier'
]);

export const zStaffProfileDao = z.object({
    department: zStaffDepartmentEnum
});

export const zDoctorProfileDao = z.object({
    specialty: z.union([
        z.string(),
        z.null()
    ]).optional(),
    sip_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    str_number: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zGenderEnum = z.enum([
    'L',
    'P'
]);

export const zBloodTypeEnum = z.enum([
    'A',
    'B',
    'AB',
    'O',
    'A+',
    'A-',
    'B+',
    'B-',
    'AB+',
    'AB-',
    'O+',
    'O-'
]);

export const zPatientProfileDao = z.object({
    nik: z.string(),
    bpjs_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    date_of_birth: z.string().date(),
    gender: zGenderEnum,
    blood_type: z.union([
        zBloodTypeEnum,
        z.null()
    ]).optional(),
    address: z.union([
        z.string(),
        z.null()
    ]).optional(),
    emergency_contact_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    emergency_contact_phone: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUserProfileDao = z.object({
    id: z.string().uuid(),
    username: z.string(),
    full_name: z.string(),
    email: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    role: z.string(),
    photo_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    is_active: z.boolean(),
    details: z.union([
        zStaffProfileDao,
        zDoctorProfileDao,
        zPatientProfileDao,
        z.null()
    ]).optional()
});

export const zApiResponseUserProfileDao = z.object({
    success: z.boolean(),
    data: z.union([
        zUserProfileDao,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zApiResponseVisitDto = z.object({
    success: z.boolean(),
    data: z.union([
        zVisitDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zWearableDeviceDto = z.object({
    device_identifier: z.string(),
    device_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    device_type: z.union([
        z.string(),
        z.null()
    ]).optional(),
    is_active: z.boolean().optional().default(true),
    id: z.string().uuid(),
    patient_id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zApiResponseWearableDeviceDto = z.object({
    success: z.boolean(),
    data: z.union([
        zWearableDeviceDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zWearableMeasurementDto = z.object({
    recorded_at: z.string().datetime(),
    heart_rate: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    systolic_bp: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    diastolic_bp: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    body_temperature: z.union([
        z.number(),
        z.null()
    ]).optional(),
    steps: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    spo2: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    id: z.string().uuid(),
    device_id: z.string().uuid(),
    created_at: z.string().datetime()
});

export const zApiResponseWearableMeasurementDto = z.object({
    success: z.boolean(),
    data: z.union([
        zWearableMeasurementDto,
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBodyLogoutApiAuthLogoutPost = z.object({
    refresh_token: z.string()
});

export const zBodyRefreshTokenApiAuthRefreshPost = z.object({
    refresh_token: z.string()
});

export const zBodyUpdateLabOrderApiLabOrdersOrderIdPatch = z.object({
    order_status: z.string(),
    result_value: z.union([
        z.string(),
        z.null()
    ]).optional(),
    result_unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    interpretation: z.union([
        z.string(),
        z.null()
    ]).optional(),
    file: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBodyUpdateReferralApiReferralsReferralIdPut = z.object({
    referred_to_facility: z.union([
        z.string(),
        z.null()
    ]).optional(),
    specialty: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reason: z.union([
        z.string(),
        z.null()
    ]).optional(),
    diagnosis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    referral_status: z.union([
        z.string(),
        z.null()
    ]).optional(),
    file: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zClinicCreateDto = z.object({
    name: z.string()
});

export const zClinicUpdateDto = z.object({
    name: z.string()
});

export const zCreateUserDto = z.object({
    username: z.string().min(3).max(50),
    password: z.string().min(6),
    full_name: z.string().min(1).max(150),
    email: z.union([
        z.string().email(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    role: z.string()
});

export const zFieldError = z.object({
    field: z.string(),
    message: z.string(),
    tag: z.string(),
    details: z.object({}).optional()
});

export const zErrorResponse = z.object({
    success: z.boolean(),
    data: z.null().optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    errors: z.union([
        z.array(zFieldError),
        z.null()
    ]).optional()
});

export const zInvoiceItemCreateDto = z.object({
    item_type: z.string(),
    description: z.string(),
    quantity: z.number().int(),
    unit_price: z.number().gte(0)
});

export const zInvoiceCreateDto = z.object({
    visit_id: z.string().uuid(),
    items: z.union([
        z.array(zInvoiceItemCreateDto),
        z.null()
    ]).optional(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zInvoiceUpdateDto = z.object({
    total_amount: z.union([
        z.number(),
        z.null()
    ]).optional(),
    amount_paid: z.union([
        z.number(),
        z.null()
    ]).optional(),
    payment_status: z.union([
        z.string(),
        z.null()
    ]).optional(),
    payment_method: z.union([
        z.string(),
        z.null()
    ]).optional(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    items: z.union([
        z.array(zInvoiceItemCreateDto),
        z.null()
    ]).optional()
});

export const zLabOrderCreateDto = z.object({
    lab_test_id: z.string().uuid(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    visit_id: z.string().uuid()
});

export const zLabTestCreateDto = z.object({
    test_code: z.string(),
    test_name: z.string(),
    category: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reference_range: z.union([
        z.string(),
        z.null()
    ]).optional(),
    price: z.number().gte(0).optional().default(0),
    is_active: z.boolean().optional().default(true)
});

export const zLabTestUpdateDto = z.object({
    test_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    test_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    category: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reference_range: z.union([
        z.string(),
        z.null()
    ]).optional(),
    price: z.union([
        z.number(),
        z.null()
    ]).optional(),
    is_active: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

export const zLoginDto = z.object({
    username: z.string(),
    password: z.string()
});

export const zMedicalRecordCreateDto = z.object({
    anamnesis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    physical_exam: z.union([
        z.string(),
        z.null()
    ]).optional(),
    diagnosis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    treatment_plan: z.union([
        z.string(),
        z.null()
    ]).optional(),
    doctor_notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    outcome: z.union([
        zOutcomeEnum,
        z.null()
    ]).optional(),
    visit_id: z.string().uuid()
});

export const zMedicalRecordUpdateDto = z.object({
    anamnesis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    physical_exam: z.union([
        z.string(),
        z.null()
    ]).optional(),
    diagnosis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    treatment_plan: z.union([
        z.string(),
        z.null()
    ]).optional(),
    doctor_notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    outcome: z.union([
        zOutcomeEnum,
        z.null()
    ]).optional()
});

export const zMedicineCreateDto = z.object({
    medicine_code: z.string(),
    medicine_name: z.string(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit_price: z.number().optional().default(0),
    is_active: z.boolean().optional().default(true)
});

export const zMedicineUpdateDto = z.object({
    medicine_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    medicine_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit_price: z.union([
        z.number(),
        z.null()
    ]).optional(),
    is_active: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

export const zPaginationMetaModel = z.object({
    limit: z.number().int(),
    total: z.number().int(),
    total_page: z.number().int(),
    current_page: z.number().int()
});

export const zPaginatedApiResponseListClinicDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zClinicDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListInvoiceDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zInvoiceDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListLabOrderDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zLabOrderDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListLabTestDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zLabTestDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListMedicalRecordDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zMedicalRecordDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListMedicineDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zMedicineDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListPrescriptionDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zPrescriptionDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListReferralDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zReferralDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListUserDao = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zUserDao),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListVisitDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zVisitDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListWearableDeviceDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zWearableDeviceDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPaginatedApiResponseListWearableMeasurementDto = z.object({
    success: z.boolean(),
    data: z.union([
        z.array(zWearableMeasurementDto),
        z.null()
    ]).optional(),
    message: z.union([
        z.string(),
        z.null()
    ]).optional(),
    meta: z.union([
        zPaginationMetaModel,
        z.object({})
    ])
});

export const zPrescriptionItemCreateDto = z.object({
    medicine_id: z.string().uuid(),
    quantity: z.number().int(),
    dosage: z.union([
        z.string(),
        z.null()
    ]).optional(),
    frequency: z.union([
        z.string(),
        z.null()
    ]).optional(),
    duration: z.union([
        z.string(),
        z.null()
    ]).optional(),
    instructions: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zPrescriptionCreateDto = z.object({
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    visit_id: z.string().uuid(),
    items: z.array(zPrescriptionItemCreateDto)
});

export const zPrescriptionStatusEnum = z.enum([
    'pending',
    'processing',
    'completed',
    'canceled'
]);

export const zPrescriptionUpdateDto = z.object({
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    items: z.union([
        z.array(zPrescriptionItemCreateDto),
        z.null()
    ]).optional()
});

export const zPrescriptionUpdateStatusDto = z.object({
    prescription_status: zPrescriptionStatusEnum,
    pharmacy_staff_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zReferralCreateDto = z.object({
    referred_to_facility: z.string(),
    specialty: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reason: z.string(),
    diagnosis: z.union([
        z.string(),
        z.null()
    ]).optional(),
    notes: z.union([
        z.string(),
        z.null()
    ]).optional(),
    visit_id: z.string().uuid()
});

export const zRegisterDto = z.object({
    username: z.string().min(3).max(50),
    password: z.string().min(6),
    full_name: z.string().min(1).max(150),
    email: z.union([
        z.string().email(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUpdateAdminProfileDto = z.object({
    full_name: z.union([
        z.string().min(1).max(150),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().regex(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string().max(20),
        z.null()
    ]).optional()
});

export const zUpdateDoctorProfileDto = z.object({
    full_name: z.union([
        z.string().min(1).max(150),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().regex(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string().max(20),
        z.null()
    ]).optional(),
    specialty: z.union([
        z.string(),
        z.null()
    ]).optional(),
    sip_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    str_number: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUpdatePatientProfileDto = z.object({
    full_name: z.union([
        z.string().min(1).max(150),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().regex(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string().max(20),
        z.null()
    ]).optional(),
    nik: z.union([
        z.string().length(16),
        z.null()
    ]).optional(),
    bpjs_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    date_of_birth: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    gender: z.union([
        zGenderEnum,
        z.null()
    ]).optional(),
    blood_type: z.union([
        zBloodTypeEnum,
        z.null()
    ]).optional(),
    address: z.union([
        z.string(),
        z.null()
    ]).optional(),
    emergency_contact_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    emergency_contact_phone: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUpdateStaffProfileDto = z.object({
    full_name: z.union([
        z.string().min(1).max(150),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().regex(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string().max(20),
        z.null()
    ]).optional(),
    department: z.union([
        zStaffDepartmentEnum,
        z.null()
    ]).optional()
});

export const zVisitCreateDto = z.object({
    visit_type: zVisitTypeEnum.optional(),
    chief_complaint: z.union([
        z.string(),
        z.null()
    ]).optional(),
    visit_datetime: z.string().datetime().optional(),
    patient_id: z.string().uuid(),
    doctor_id: z.string().uuid(),
    clinic_id: z.string().uuid()
});

export const zVisitUpdateDto = z.object({
    visit_type: z.union([
        zVisitTypeEnum,
        z.null()
    ]).optional(),
    chief_complaint: z.union([
        z.string(),
        z.null()
    ]).optional(),
    visit_datetime: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    visit_status: z.union([
        zVisitStatusEnum,
        z.null()
    ]).optional(),
    doctor_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    clinic_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zWearableDeviceCreateDto = z.object({
    device_identifier: z.string(),
    device_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    device_type: z.union([
        z.string(),
        z.null()
    ]).optional(),
    is_active: z.boolean().optional().default(true)
});

export const zWearableDeviceUpdateDto = z.object({
    device_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    device_type: z.union([
        z.string(),
        z.null()
    ]).optional(),
    is_active: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

export const zWearableMeasurementCreateDto = z.object({
    recorded_at: z.string().datetime(),
    heart_rate: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    systolic_bp: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    diastolic_bp: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    body_temperature: z.union([
        z.number(),
        z.null()
    ]).optional(),
    steps: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    spo2: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zLoginApiAuthLoginPostResponse = zApiResponseTokenDao;

export const zLogoutApiAuthLogoutPostResponse = zApiResponseNoneType;

export const zRefreshTokenApiAuthRefreshPostResponse = zApiResponseTokenDao;

export const zRegisterApiAuthRegisterPostResponse = zApiResponseUserDao;

export const zListUsersApiUsersGetResponse = zPaginatedApiResponseListUserDao;

export const zCreateUserApiUsersPostResponse = zApiResponseUserDao;

export const zListClinicsApiClinicsGetResponse = zPaginatedApiResponseListClinicDto;

export const zCreateClinicApiClinicsPostResponse = zApiResponseClinicDto;

export const zDeleteClinicApiClinicsClinicIdDeleteResponse = zApiResponse;

export const zGetClinicApiClinicsClinicIdGetResponse = zApiResponseClinicDto;

export const zUpdateClinicApiClinicsClinicIdPutResponse = zApiResponseClinicDto;

export const zGetMyProfileApiProfileMeGetResponse = zApiResponseUserProfileDao;

export const zUpdateAdminProfileApiProfileAdminPutResponse = zApiResponse;

export const zUpdateStaffProfileApiProfileStaffPutResponse = zApiResponseUserProfileDao;

export const zUpdateDoctorProfileApiProfileDoctorPutResponse = zApiResponseUserProfileDao;

export const zUpdatePatientProfileApiProfilePatientPutResponse = zApiResponseUserProfileDao;

export const zListVisitsApiVisitsGetResponse = zPaginatedApiResponseListVisitDto;

export const zCreateVisitApiVisitsPostResponse = zApiResponseVisitDto;

export const zDeleteVisitApiVisitsVisitIdDeleteResponse = zApiResponse;

export const zGetVisitApiVisitsVisitIdGetResponse = zApiResponseVisitDto;

export const zUpdateVisitApiVisitsVisitIdPutResponse = zApiResponseVisitDto;

export const zListMedicalRecordsApiMedicalRecordsGetResponse = zPaginatedApiResponseListMedicalRecordDto;

export const zCreateMedicalRecordApiMedicalRecordsPostResponse = zApiResponseMedicalRecordDto;

export const zDeleteMedicalRecordApiMedicalRecordsRecordIdDeleteResponse = zApiResponse;

export const zGetMedicalRecordApiMedicalRecordsRecordIdGetResponse = zApiResponseMedicalRecordDto;

export const zUpdateMedicalRecordApiMedicalRecordsRecordIdPutResponse = zApiResponseMedicalRecordDto;

export const zListMedicinesApiMedicinesGetResponse = zPaginatedApiResponseListMedicineDto;

export const zCreateMedicineApiMedicinesPostResponse = zApiResponseMedicineDto;

export const zDeleteMedicineApiMedicinesMedicineIdDeleteResponse = zApiResponse;

export const zGetMedicineApiMedicinesMedicineIdGetResponse = zApiResponseMedicineDto;

export const zUpdateMedicineApiMedicinesMedicineIdPutResponse = zApiResponseMedicineDto;

export const zListPrescriptionsApiPrescriptionsGetResponse = zPaginatedApiResponseListPrescriptionDto;

export const zCreatePrescriptionApiPrescriptionsPostResponse = zApiResponsePrescriptionDto;

export const zGetPrescriptionApiPrescriptionsPrescriptionIdGetResponse = zApiResponsePrescriptionDto;

export const zUpdatePrescriptionApiPrescriptionsPrescriptionIdPutResponse = zApiResponsePrescriptionDto;

export const zUpdatePrescriptionStatusApiPrescriptionsPrescriptionIdStatusPatchResponse = zApiResponsePrescriptionDto;

export const zListLabTestsApiLabTestsGetResponse = zPaginatedApiResponseListLabTestDto;

export const zCreateLabTestApiLabTestsPostResponse = zApiResponseLabTestDto;

export const zDeleteLabTestApiLabTestsTestIdDeleteResponse = zApiResponse;

export const zGetLabTestApiLabTestsTestIdGetResponse = zApiResponseLabTestDto;

export const zUpdateLabTestApiLabTestsTestIdPutResponse = zApiResponseLabTestDto;

export const zListLabOrdersApiLabOrdersGetResponse = zPaginatedApiResponseListLabOrderDto;

export const zCreateLabOrderApiLabOrdersPostResponse = zApiResponseLabOrderDto;

export const zGetLabOrderApiLabOrdersOrderIdGetResponse = zApiResponseLabOrderDto;

export const zUpdateLabOrderApiLabOrdersOrderIdPatchResponse = zApiResponseLabOrderDto;

export const zListReferralsApiReferralsGetResponse = zPaginatedApiResponseListReferralDto;

export const zCreateReferralApiReferralsPostResponse = zApiResponseReferralDto;

export const zDeleteReferralApiReferralsReferralIdDeleteResponse = zApiResponse;

export const zGetReferralApiReferralsReferralIdGetResponse = zApiResponseReferralDto;

export const zUpdateReferralApiReferralsReferralIdPutResponse = zApiResponseReferralDto;

export const zListInvoicesApiInvoicesGetResponse = zPaginatedApiResponseListInvoiceDto;

export const zCreateInvoiceApiInvoicesPostResponse = zApiResponseInvoiceDto;

export const zDeleteInvoiceApiInvoicesInvoiceIdDeleteResponse = zApiResponse;

export const zGetInvoiceApiInvoicesInvoiceIdGetResponse = zApiResponseInvoiceDto;

export const zUpdateInvoiceApiInvoicesInvoiceIdPutResponse = zApiResponseInvoiceDto;

export const zListDevicesApiWearablesDevicesGetResponse = zPaginatedApiResponseListWearableDeviceDto;

export const zCreateDeviceApiWearablesDevicesPostResponse = zApiResponseWearableDeviceDto;

export const zDeleteDeviceApiWearablesDevicesDeviceIdDeleteResponse = zApiResponse;

export const zGetDeviceApiWearablesDevicesDeviceIdGetResponse = zApiResponseWearableDeviceDto;

export const zUpdateDeviceApiWearablesDevicesDeviceIdPutResponse = zApiResponseWearableDeviceDto;

export const zListMeasurementsApiWearablesDevicesDeviceIdMeasurementsGetResponse = zPaginatedApiResponseListWearableMeasurementDto;

export const zAddMeasurementApiWearablesDevicesDeviceIdMeasurementsPostResponse = zApiResponseWearableMeasurementDto;